# .github/workflows/deploy.yml
name: Deploy S3 Website via Terraform Cloud

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch
  workflow_dispatch: # Allows manual trigger from GitHub UI

 

jobs:
  terraform_plan_and_apply:
    runs-on: ubuntu-latest
    environment: YOUR_TERRAFORM_CLOUD_WORKSPACE_ENVIRONMENT # Optional: If you use GitHub Environments for approvals
    
    env:
      AWS_EC2_METADATA_DISABLED: true # Disable EC2 metadata service for security reasons
      # Pass GitHub Secrets to Terraform variables using TF_VAR_ prefix
      PLAN_FILENAME: tfplan
      TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set AWS_EC2_METADATA_DISABLED for all subsequent steps
        run: echo "AWS_EC2_METADATA_DISABLED=true" >> $GITHUB_ENV
        # This writes the environment variable to a special file that GitHub Actions
        # reads and applies to all *subsequent* steps in the same job.
        # This is generally more reliable for critical environment variables.

       # --- ADD THESE LINES HERE FOR AWS CREDENTIALS ---
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Make sure this matches your S3 bucket region, or dynamically set it
      # --- END ADDITION ---
      
      
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4 # Match your TFC version or use a compatible one
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }} # TFC API Token

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan_output_step
        run: terraform plan -no-color -out=${{ env.PLAN_FILENAME }} # Save the plan
        

      - name: Check Terraform Plan Results
        id: plan_check # This ID is correct for your conditional logic
        # No 'env:' block for PLAN here, as we are getting it directly from `terraform show`

        run: |
          # Use 'terraform show' to get the human-readable output from the binary plan file
          PLAN_OUTPUT=$(terraform show -no-color ${{ env.PLAN_FILENAME }})

          echo "DEBUG: Raw plan output relevant lines for change detection:"
          echo "$PLAN_OUTPUT" | grep -E "No changes.|Plan: [0-9]+ to add, [0-9]+ to change, [0-9]+ to destroy." || true # print only relevant lines
          echo "--------------------------------------------------------"

          if echo "$PLAN_OUTPUT" | grep -q "No changes."; then
            echo "::notice file=main.tf::Terraform plan found no changes. Skipping apply."
            echo "has_changes=false" >> $GITHUB_OUTPUT # Correct syntax for setting output
            echo "DEBUG: has_changes set to false" 
          else 
            echo "::notice file=main.tf::Terraform plan found changes. Proceeding with apply."
            echo "has_changes=true" >> $GITHUB_OUTPUT # Correct syntax for setting output
            echo "DEBUG: has_changes set to true"
          fi 

        # Make sure `terraform show` output is not too large for `PLAN_OUTPUT` var if it's huge.
        # For most static sites, it will be fine.


      - name: Generate Terraform Plan Summary Markdown # Renamed for clarity
        id: generate_summary # Keep this ID if you reference it elsewhere
        run: |
          PLAN_PATH=${{ env.PLAN_FILENAME }} # Path to the binary plan file
          # Use `terraform show` to get the human-readable output to parse
          TERRAFORM_PLAN_OUTPUT=$(terraform show -no-color "$PLAN_PATH")

          # Initialize a variable to hold the summary content
          SUMMARY_CONTENT=""

          # Check for no changes from the 'terraform show' output
          if echo "$TERRAFORM_PLAN_OUTPUT" | grep -q "No changes. Your infrastructure matches the configuration."; then
            SUMMARY_CONTENT="## :white_check_mark: No changes detected.\nYour infrastructure perfectly matches the Terraform configuration."
          elif echo "$TERRAFORM_PLAN_OUTPUT" | grep -q "No changes. No objects need to be destroyed."; then # Fallback for older message
            SUMMARY_CONTENT="## :white_check_mark: No changes detected.\nEither you have not created any objects yet or the existing objects were already deleted outside of Terraform."
          else
            # If there ARE changes, build the detailed table
            SUMMARY_CONTENT+="## :bulb: Terraform Plan Details\n"
            SUMMARY_CONTENT+="| Action | Resource |\n"
            SUMMARY_CONTENT+="|--------|----------|\n"

            # Extract and format resource changes
            CHANGES=$(echo "$TERRAFORM_PLAN_OUTPUT" | grep -E '^\S+ \S+\.\S+ (will be|must be|has been)' | \
            sed -e 's/^\([+-~]\)\s\+\(.*\)\s\+will be created/|:white_check_mark: create|\2|/' \
                -e 's/^\([+-~]\)\s\+\(.*\)\s\+will be destroyed/|:bangbang: destroy|\2|/' \
                -e 's/^\([+-~]\)\s\+\(.*\)\s\+will be replaced/|:recycle: replace|\2|/' \
                -e 's/^\([+-~]\)\s\+\(.*\)\s\+must be replaced/|:recycle: replace|\2|/' \
                -e 's/^\([+-~]\)\s\+\(.*\)\s\+will be updated in-place/|:arrows_counterclockwise: update|\2|/' \
                -e 's/^\([+-~]\)\s\+\(.*\)\s\+has been tainted/|:warning: tainted|\2|/')

            SUMMARY_CONTENT+="$CHANGES\n\n" # Add the extracted changes

            # Print the final plan summary line (e.g., "Plan: X to add, Y to change, Z to destroy.")
            PLAN_SUMMARY_LINE=$(echo "$TERRAFORM_PLAN_OUTPUT" | grep -E '^Plan:|^Changes to Outputs:' | sed -e 's/^/## /')
            SUMMARY_CONTENT+="$PLAN_SUMMARY_LINE"
          fi

          # Write the collected content to the markdown file
          # IMPORTANT: This creates/overwrites plan_summary.md
          echo "$SUMMARY_CONTENT" > plan_summary.md

          # You no longer need to write to GITHUB_STEP_SUMMARY directly here,
          # as the next 'Update Workflow Run Summary with Plan' step will do it.
          # Remove this line:
          # cat plan_summary.md >> $GITHUB_STEP_SUMMARY

      - name: Update Workflow Run Summary with Plan
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('plan_summary.md', 'utf8');
            await core.summary.addRaw(summary).write();
            console.log("Workflow Run Summary updated successfully.");
          # Parameters for actions/github-script itself (like github-token, debug)
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          debug: true # Enable debug logging for this step

      # Manual approval (optional, but good for CD)
      - name: Await Manual Approval
        if: github.event_name == 'pull_request' && steps.plan_check.outputs.has_changes == 'true'
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }} # GitHub Token for API access
          approvers: pavan-bethanabotla-infosrc # Replace with GitHub username(s) or team(s)
          minimum-approvals: 1
          issue-title: "Approve Terraform Apply for ${{ github.ref }}"
          issue-body: "A Terraform plan is ready for review. Click 'Approve' to proceed with apply."
          exclude-workflow-initiator: false
      
      - name: Debug has_changes Output (Pre-Apply Check)
        # This step will run right before the apply.
        # It's here to definitively show what value is available for the if condition.
        run: |
          echo "Value of steps.plan_check.outputs.has_changes directly before apply: '${{ steps.plan_check.outputs.has_changes }}'"
          # Add a test of the full condition. GitHub Actions evaluates this on the fly.
          echo "Full apply condition evaluation (should be false if no changes): ${{ github.event_name != 'pull_request' && steps.plan_check.outputs.has_changes == 'true' }}"
        # Ensure this debug step always runs so we can see its output.
        if: always()

      - name: Terraform Apply
        # Apply only if:
        # 1. The event is NOT a pull request (e.g., it's a push to main) AND
        # 2. The plan detected actual changes
        if: github.ref == 'refs/heads/main' && success() && steps.plan_check.outputs.has_changes == 'true' 
        run: terraform apply -auto-approve ${{ env.PLAN_FILENAME }} # Apply the saved plan file